[project]
name = "everybody-codes"
version = "0.1.0"
description = "my solutions for everybody.codes exercises"
requires-python = ">=3.14"
dependencies = [
    "pytest>=8.4.2",
    "ruff>=0.14.3",
    "ty>=0.0.1a25",
]

[tool.ruff.lint.isort]
force-single-line = true